name: tauon
version: git
adopt-info: tauon

grade: stable
confinement: strict
base: core18

architectures:
  - amd64

apps:
  tauon:
    command: tauon.py
    common-id: tauonmb
    desktop: usr/share/applications/tauonmb.desktop
    environment:
      PYSDL2_DLL_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    extensions:
      - gnome-3-28
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - network
      - removable-media
      - gsettings
      - opengl
      - audio-playback
      - pulseaudio
    slots:
    - mpris

parts:
  desktop-icon:
    source: .
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps
      cp -v extra/tauonmb.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/
      cp -v extra/tauonmb.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/
      cp -v extra/tauonmb-symbolic.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/
      sed -i 's|Icon=tauonmb|Icon=/usr/share/icons/hicolor/scalable/apps/tauonmb.svg|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/tauonmb.desktop
      snapcraftctl build

  python-deps:
    plugin: python
    source: .
    python-version: python3
    requirements:
      - requirements.txt
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - fonts-noto
      - python3-gi
      - python3-cairo
      - python3-dbus
      - python-gst-1.0
      - python3-gi-cairo
      - gir1.2-notify-0.7
      - gir1.2-rsvg-2.0
      - gir1.2-appindicator3-0.1
      - freeglut3-dev
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-libav
      - libgpm2
      - libslang2
      - libpulse0
      - libglu1-mesa
      - libgl1
      - ffmpeg
      - p7zip-full
      - unrar
      - curl

    override-build: |
      snapcraftctl build
      # temp fix for https://github.com/marcusva/py-sdl2/issues/148
      cd $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      ln -sf libSDL2-2.0.so.0 libSDL2-2.0.so
      ln -sf libSDL2_image-2.0.so.0 libSDL2_image-2.0.so
      
  tauon:
    plugin: dump
    source: .
    parse-info: [extra/com.github.taiko2k.tauonmb.appdata.xml]
    build-packages:
      - gettext
      - libflac-dev
      - libpulse-dev
      - libvorbis-dev
      - libopusfile-dev
      - libmpg123-dev
      - libsamplerate0-dev
      - libopenmpt-dev
    stage-packages:
      - flac
      - libpulse0
      - libvorbis0a
      - libopusfile0
      - libmpg123-0
      - libsamplerate0
      - libopenmpt0
      
    override-build: |
      chmod +x compile-translations.py
      python3 compile-translations.py
      bash compile-phazor.sh
      snapcraftctl build
      chmod +x tauon.py

 
