name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest # action can only be run on windows
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Taiko2k.TauonMusicBox
          token: ${{ secrets.WINGET_TOKEN }}
